### ISSUE TITLE
MethodDeclaration.usages should include usages by lambdas

### ISSUE THREAD

**Issue by pleschev** [rpau/javalang-compiler#76]
I have previously raised https://github.com/walkmod/walkmod-dead-code-cleaner-plugin/issues/4 where code was incorrectly deleted because classes & methods that were being used in lambdas were incorrectly being identified as unused. The dead code cleaner plugin uses MethodDeclaration.usages to determine whether a method is in use or not. This list is not being populated with usages from lambdas.

**Comment by pleschev** [comment]
I have created a test case that recreates the problem. Please see PR#77 

Any guidance on how to fix the problem would be much appreciated

**Comment by rpau** [comment]
Fixed here: https://github.com/rpau/javalang-compiler/pull/78

**Comment by pleschev** [comment]
Thank you for fixing this! I've raised #79 which is a similar corner case,
